"use client";

import { useEffect, useRef } from "react";

// Approved portfolio content preserved from the previous static release.
export type PortfolioSection = "story" | "work" | "results" | "contact";

export function PortfolioContent({ section }: { section: PortfolioSection }) {
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const track = root.current?.querySelector<HTMLElement>("[data-admission-track]");
    const previous = root.current?.querySelector<HTMLButtonElement>("[data-carousel-prev]");
    const next = root.current?.querySelector<HTMLButtonElement>("[data-carousel-next]");
    if (!track || !previous || !next) return;
    const scroll = (direction: number) => {
      const first = track.firstElementChild as HTMLElement | null;
      const step = (first?.getBoundingClientRect().width ?? track.clientWidth) + 22;
      track.scrollBy({ left: direction * step, behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth" });
    };
    const back = () => scroll(-1);
    const forward = () => scroll(1);
    previous.addEventListener("click", back);
    next.addEventListener("click", forward);
    return () => {
      previous.removeEventListener("click", back);
      next.removeEventListener("click", forward);
    };
  }, [section]);
  return <div ref={root} className="portfolio-content">
{section === "story" && <><section className="thread" id="story"><div className="wrap"><div className="section-top"><span className="mono">How it started</span><div><h2>Not a master plan. A chain of problems.</h2><p>I did not begin with “I want to build a startup.” Each step started with something that bothered me enough to investigate.</p></div></div><div className="timeline"><article className="entry"><span className="pin"></span><div><span className="date mono">2024 · The expensive lesson</span><h3>I lost about $500 in a Telegram crypto scam.</h3><p>I was embarrassed, then curious. I traced wallets, learned OSINT, moved to Linux, studied the OWASP Top 10, and completed more than 25 security labs. A bad decision became the reason I learned how trust fails online.</p></div></article><article className="entry"><span className="pin"></span><div><span className="date mono">2025 · The first real users</span><h3>A movie bot taught me that shipping changes the questions.</h3><p>Movistan eventually served more than 800 people and handled around 1,200 daily searches at its busiest. The hard part stopped being “can I code this?” and became reliability, confused users, and fixing the same edge case twice.</p></div></article><article className="entry"><span className="pin"></span><div><span className="date mono">2026 · Closer to home</span><h3>I started choosing problems I could observe myself.</h3><p>That led to pickup ordering for bazaar kitchens, offline driving-test practice, and a private remote-work tool. The projects are different; the instinct is the same: reduce one piece of friction, then listen.</p></div></article></div></div></section>
<section className="admissions" aria-labelledby="admissions-title"><div className="wrap admissions-head"><div><span className="mono">Three yeses I could not take</span><h2 id="admissions-title">Acceptance was not the finish line.</h2></div><div className="carousel-controls" aria-label="University stories"><button type="button" data-carousel-prev aria-label="Previous university">←</button><button type="button" data-carousel-next aria-label="Next university">→</button></div></div><div className="admission-track" data-admission-track tabIndex={0}>
<article className="admission-card"><div className="admission-letter"><img src="/portfolio/floridatech-acceptance.webp" alt="Florida Tech admission letter for Xayrillo Ne'matov" loading="lazy" /></div><div className="admission-copy"><span className="mono">01 · Florida Tech · January 2026</span><h3>The first letter made the possibility real.</h3><p>Florida Tech admitted me to its BS Computer Science program. Until that email, studying in the United States was mostly an application portal, essays, and waiting. This was the first concrete yes.</p><p className="fact">The offer proved I could compete internationally. It did not solve the cost of attending.</p></div></article>
<article className="admission-card"><div className="admission-letter"><img src="/portfolio/rit-acceptance.webp" alt="RIT admission letter for Xayrillo Ne'matov" loading="lazy" /></div><div className="admission-copy"><span className="mono">02 · RIT · March 2026</span><h3>The strongest offer became the hardest no.</h3><p>RIT admitted me to Cybersecurity and later awarded a renewable $23,000 annual scholarship—up to $92,000 over four years. It was the program closest to the work that first pulled me into technology.</p><p className="fact">Even after the scholarship, the remaining cost was beyond what my family could afford. I was admitted, but I could not enroll.</p></div></article>
<article className="admission-card"><div className="admission-letter"><img src="/portfolio/pennstate-acceptance.webp" alt="Penn State Harrisburg admission letter for Xayrillo Ne'matov" loading="lazy" /></div><div className="admission-copy"><span className="mono">03 · Penn State · March 2026</span><h3>A third yes clarified the real constraint.</h3><p>Penn State Harrisburg offered me a place in Cybersecurity Analytics and Operations. By then, the pattern was clear: the obstacle was not whether a university would admit me.</p><p className="fact">The obstacle was affordability. I stayed in Uzbekistan, took the lesson seriously, and kept building instead of treating an offer letter as the final achievement.</p></div></article>
</div><div className="wrap carousel-hint mono">Swipe or use the arrows · 01—03</div></section>
</>}
{section === "work" && <section className="work" id="work"><div className="wrap"><span className="mono">Things I have made</span><h2>Useful before impressive.</h2>
<article className="project"><div className="project-copy"><span className="mono">01 · Food, without the queue</span><h3>Nma Yeymiz</h3><p>A Telegram-first pickup tool for bazaar kitchens. Customers browse, order ahead, and collect when the food is ready. The idea came from watching delivery products solve the wrong problem for places where people are already nearby.</p><div className="tiny-result"><b>Honest status</b><span>The product works; adoption is the unfinished part. Convincing busy kitchen owners is harder than writing the order flow.</span></div><a href="https://nmayeymiz.uz" target="_blank" rel="noreferrer">Open the product ↗</a></div><div className="project-visual logo-only"><img src="/portfolio/nmayeymiz.webp" alt="Nma Yeymiz logo" loading="lazy" /></div></article>
<article className="project"><div className="project-copy"><span className="mono">02 · The difficult build</span><h3>Hamma</h3><p>A cross-platform SSH/SFTP client shaped by zero-trust thinking. I built connection recovery, encrypted credential storage, file transfer, packaging, and CI across Flutter targets.</p><div className="tiny-result"><b>What broke</b><span>A stale-connection bug exposed the lack of integration tests. An audit also found unsigned builds and weak backup-key derivation. I treated that report as a roadmap, not an insult.</span></div><a href="https://github.com/xayrullonematov/hamma" target="_blank" rel="noreferrer">Read the code ↗</a></div><div className="project-visual logo-only hamma"><img src="/portfolio/hamma-logo.webp" alt="Hamma logo" loading="lazy" /></div></article>
<article className="project"><div className="project-copy"><span className="mono">03 · Learning without signal</span><h3>Autotestlar.uz</h3><p>Driving-exam practice for Uzbek learners, with an offline-first mobile direction. It began as a website; rebuilding it around local storage and sync forced me to think beyond the happy path.</p><div className="tiny-result"><b>Small lesson</b><span>“Offline-first” is not a feature badge. It changes how every question, answer, and update is stored.</span></div><a href="https://autotestlar.uz" target="_blank" rel="noreferrer">Visit Autotestlar ↗</a></div><div className="project-visual logo-only auto"><img src="/portfolio/autotestlar-logo.webp" alt="Autotestlar.uz logo" loading="lazy" /></div></article>
</div></section>
}
{section === "results" && <section className="receipts" id="results"><div className="wrap"><span className="mono">A few small receipts</span><h2>Results I’m quietly proud of.</h2><p className="lead">No inflated dashboards. Just outcomes that meant something because a real person, classroom, or decision sat behind them.</p><div className="moments"><article className="moment"><div><span className="big">1 friend</span><p>Two months of daily speaking practice helped him reach IELTS Speaking 7.</p></div><small>I learned to teach confidence before vocabulary.</small></article><article className="moment"><div><span className="big">30+ students</span><p>joined the weekly English speaking club I organized at school.</p></div><small>The format mattered: debates and activities, not another lecture.</small></article><article className="moment"><div><span className="big">Top 50</span><p>among more than 20,000 participants in the IBRAT English and critical-thinking marathon.</p></div><small>A useful signal—not a personality.</small></article></div></div></section>

}
{section === "contact" && <footer className="ending" id="contact"><div className="wrap"><span className="mono">Still learning in public</span><h2>If the problem is real, I’m interested.</h2><div className="contacts"><a href="mailto:hello@nematov.com">Email me ↗</a><a href="https://t.me/mr_khayrulloh" target="_blank" rel="noreferrer">Telegram ↗</a><a href="https://github.com/xayrullonematov" target="_blank" rel="noreferrer">GitHub ↗</a></div><div className="foot"><span>© 2026 Xayrillo Ne’matov</span><span>Built in Urgut. Continued in Tashkent.</span></div></div></footer>}

  </div>;
}
